### ISSUE TITLE
Intellij project conversion to Eclipse

### ISSUE THREAD

**Issue by Ebbeb** [AugustMoebius/DTUPay#49]
Include the projects converted to Eclipse projects, so that we can see the source
code in Eclipse
· The original IntelliJ projects

**Comment by s153762** [comment]
You can open in eclipse 2017 june, can run JUnit test, but not cucumber (because i do not have a plugin, I think). So run from terminal and see project in eclipse:

Import:

file/import/
chose maven -> from existing maven
Find project, check pom-xml, and check create project files
And the project opens automatically
